name: Scala CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check sbt formatting
      run: sbt scalafmtSbtCheck
    - name: Check code formatting
      run: sbt scalafmtCheckAll
    - name: Check headers
      run: sbt headerCheck
    - name: Run tests
      run: sbt test
